# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-23 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='primera',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='segunda',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='tercera',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=400),
        ),
    ]
