# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-23 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170923_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loterias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacional_dia', models.CharField(max_length=30)),
                ('nacional_noche', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='primera',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='segunda',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='tercera',
            field=models.IntegerField(),
        ),
    ]
